// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82Y-5aCsjvRLYpbuW07bFkrDzLmH6sEk',
    appId: '1:68369058437:web:3d0bc306aab920785c37ec',
    messagingSenderId: '68369058437',
    projectId: 'rate-it-42c0e',
    authDomain: 'rate-it-42c0e.firebaseapp.com',
    databaseURL: 'https://rate-it-42c0e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rate-it-42c0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEkt1ab3NFNTzeUdjgMFc-HHfns2vFXEU',
    appId: '1:68369058437:android:ac3d459a2494e4d25c37ec',
    messagingSenderId: '68369058437',
    projectId: 'rate-it-42c0e',
    databaseURL: 'https://rate-it-42c0e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rate-it-42c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnFmAohYh9T1Mt8I9_cuUGHjKOXX8enJA',
    appId: '1:68369058437:ios:2d72201aa171a3fa5c37ec',
    messagingSenderId: '68369058437',
    projectId: 'rate-it-42c0e',
    databaseURL: 'https://rate-it-42c0e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rate-it-42c0e.appspot.com',
    iosClientId: '68369058437-asfti6vgj953khkm42j6u7mr7h64naqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnFmAohYh9T1Mt8I9_cuUGHjKOXX8enJA',
    appId: '1:68369058437:ios:2d72201aa171a3fa5c37ec',
    messagingSenderId: '68369058437',
    projectId: 'rate-it-42c0e',
    databaseURL: 'https://rate-it-42c0e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rate-it-42c0e.appspot.com',
    iosClientId: '68369058437-asfti6vgj953khkm42j6u7mr7h64naqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
